import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/sidebar/control";
const inter = Inter({ subsets: ["latin"] });
import { cookies } from "next/headers";
import { decrypt } from "@/lib/session";
import { getUser, verifySession } from "@/lib/dal";

export const metadata: Metadata = {
  title: "MCEP-CPL - Cadastro Municipal de Empresas Penalisadas",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //busca o usuario logado baseado no id da sessao para controle de acesso
  // const hassession = await verifySession();
  // if (hassession.isAuth)
  // const usuario = await getUser();
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className=" flex">
          {/* {usuario ? <Sidebar people={usuario} /> : null} */}
          {<Sidebar />}
          <div className=" font-semibold flex-col h-screen w-screen">
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
